coverage:
  status:
    project:
      default:
        target: auto
    patch:
      default:
        target: auto

ignore:
  - "server/cmd/**"
  - "server/pkg/**"
  - "server/internal/*/mocks/**"
  - "**/*_test.go"
