// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: server/proto/account.proto

package account

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerName     string                 `protobuf:"bytes,1,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_server_proto_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_account_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAccountRequest) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_server_proto_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_account_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BlockAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockAccountRequest) Reset() {
	*x = BlockAccountRequest{}
	mi := &file_server_proto_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockAccountRequest) ProtoMessage() {}

func (x *BlockAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockAccountRequest.ProtoReflect.Descriptor instead.
func (*BlockAccountRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_account_proto_rawDescGZIP(), []int{2}
}

func (x *BlockAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UnblockAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockAccountRequest) Reset() {
	*x = UnblockAccountRequest{}
	mi := &file_server_proto_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockAccountRequest) ProtoMessage() {}

func (x *UnblockAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockAccountRequest.ProtoReflect.Descriptor instead.
func (*UnblockAccountRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_account_proto_rawDescGZIP(), []int{3}
}

func (x *UnblockAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CloseAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseAccountRequest) Reset() {
	*x = CloseAccountRequest{}
	mi := &file_server_proto_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseAccountRequest) ProtoMessage() {}

func (x *CloseAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseAccountRequest.ProtoReflect.Descriptor instead.
func (*CloseAccountRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_account_proto_rawDescGZIP(), []int{4}
}

func (x *CloseAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReserveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveRequest) Reset() {
	*x = ReserveRequest{}
	mi := &file_server_proto_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveRequest) ProtoMessage() {}

func (x *ReserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveRequest.ProtoReflect.Descriptor instead.
func (*ReserveRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_account_proto_rawDescGZIP(), []int{5}
}

func (x *ReserveRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReserveRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CreditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditRequest) Reset() {
	*x = CreditRequest{}
	mi := &file_server_proto_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditRequest) ProtoMessage() {}

func (x *CreditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditRequest.ProtoReflect.Descriptor instead.
func (*CreditRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_account_proto_rawDescGZIP(), []int{6}
}

func (x *CreditRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreditRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type DebitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebitRequest) Reset() {
	*x = DebitRequest{}
	mi := &file_server_proto_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebitRequest) ProtoMessage() {}

func (x *DebitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebitRequest.ProtoReflect.Descriptor instead.
func (*DebitRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_account_proto_rawDescGZIP(), []int{7}
}

func (x *DebitRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DebitRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CommitReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitReservationRequest) Reset() {
	*x = CommitReservationRequest{}
	mi := &file_server_proto_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitReservationRequest) ProtoMessage() {}

func (x *CommitReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitReservationRequest.ProtoReflect.Descriptor instead.
func (*CommitReservationRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_account_proto_rawDescGZIP(), []int{8}
}

func (x *CommitReservationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommitReservationRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CancelReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReservationRequest) Reset() {
	*x = CancelReservationRequest{}
	mi := &file_server_proto_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReservationRequest) ProtoMessage() {}

func (x *CancelReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReservationRequest.ProtoReflect.Descriptor instead.
func (*CancelReservationRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_account_proto_rawDescGZIP(), []int{9}
}

func (x *CancelReservationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CancelReservationRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type AccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerName     string                 `protobuf:"bytes,2,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	Balance       int64                  `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountResponse) Reset() {
	*x = AccountResponse{}
	mi := &file_server_proto_account_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountResponse) ProtoMessage() {}

func (x *AccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_account_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountResponse.ProtoReflect.Descriptor instead.
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_account_proto_rawDescGZIP(), []int{10}
}

func (x *AccountResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccountResponse) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *AccountResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *AccountResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AccountResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AccountResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_server_proto_account_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_account_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_server_proto_account_proto_rawDescGZIP(), []int{11}
}

var File_server_proto_account_proto protoreflect.FileDescriptor

const file_server_proto_account_proto_rawDesc = "" +
	"\n" +
	"\x1aserver/proto/account.proto\x12\aaccount\"5\n" +
	"\x14CreateAccountRequest\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x01 \x01(\tR\townerName\"#\n" +
	"\x11GetAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"%\n" +
	"\x13BlockAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"'\n" +
	"\x15UnblockAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"%\n" +
	"\x13CloseAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"8\n" +
	"\x0eReserveRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"7\n" +
	"\rCreditRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"6\n" +
	"\fDebitRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"B\n" +
	"\x18CommitReservationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"B\n" +
	"\x18CancelReservationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"\xb0\x01\n" +
	"\x0fAccountResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x02 \x01(\tR\townerName\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x03R\abalance\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"\a\n" +
	"\x05Empty2\xe3\x04\n" +
	"\x0eAccountService\x12A\n" +
	"\x06Create\x12\x1d.account.CreateAccountRequest\x1a\x18.account.AccountResponse\x12?\n" +
	"\aGetByID\x12\x1a.account.GetAccountRequest\x1a\x18.account.AccountResponse\x125\n" +
	"\x05Block\x12\x1c.account.BlockAccountRequest\x1a\x0e.account.Empty\x129\n" +
	"\aUnblock\x12\x1e.account.UnblockAccountRequest\x1a\x0e.account.Empty\x125\n" +
	"\x05Close\x12\x1c.account.CloseAccountRequest\x1a\x0e.account.Empty\x122\n" +
	"\aReserve\x12\x17.account.ReserveRequest\x1a\x0e.account.Empty\x120\n" +
	"\x06Credit\x12\x16.account.CreditRequest\x1a\x0e.account.Empty\x12.\n" +
	"\x05Debit\x12\x15.account.DebitRequest\x1a\x0e.account.Empty\x12F\n" +
	"\x11CommitReservation\x12!.account.CommitReservationRequest\x1a\x0e.account.Empty\x12F\n" +
	"\x11CancelReservation\x12!.account.CancelReservationRequest\x1a\x0e.account.EmptyB*Z(go-core-banking-system/pkg/proto/accountb\x06proto3"

var (
	file_server_proto_account_proto_rawDescOnce sync.Once
	file_server_proto_account_proto_rawDescData []byte
)

func file_server_proto_account_proto_rawDescGZIP() []byte {
	file_server_proto_account_proto_rawDescOnce.Do(func() {
		file_server_proto_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_proto_account_proto_rawDesc), len(file_server_proto_account_proto_rawDesc)))
	})
	return file_server_proto_account_proto_rawDescData
}

var file_server_proto_account_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_server_proto_account_proto_goTypes = []any{
	(*CreateAccountRequest)(nil),     // 0: account.CreateAccountRequest
	(*GetAccountRequest)(nil),        // 1: account.GetAccountRequest
	(*BlockAccountRequest)(nil),      // 2: account.BlockAccountRequest
	(*UnblockAccountRequest)(nil),    // 3: account.UnblockAccountRequest
	(*CloseAccountRequest)(nil),      // 4: account.CloseAccountRequest
	(*ReserveRequest)(nil),           // 5: account.ReserveRequest
	(*CreditRequest)(nil),            // 6: account.CreditRequest
	(*DebitRequest)(nil),             // 7: account.DebitRequest
	(*CommitReservationRequest)(nil), // 8: account.CommitReservationRequest
	(*CancelReservationRequest)(nil), // 9: account.CancelReservationRequest
	(*AccountResponse)(nil),          // 10: account.AccountResponse
	(*Empty)(nil),                    // 11: account.Empty
}
var file_server_proto_account_proto_depIdxs = []int32{
	0,  // 0: account.AccountService.Create:input_type -> account.CreateAccountRequest
	1,  // 1: account.AccountService.GetByID:input_type -> account.GetAccountRequest
	2,  // 2: account.AccountService.Block:input_type -> account.BlockAccountRequest
	3,  // 3: account.AccountService.Unblock:input_type -> account.UnblockAccountRequest
	4,  // 4: account.AccountService.Close:input_type -> account.CloseAccountRequest
	5,  // 5: account.AccountService.Reserve:input_type -> account.ReserveRequest
	6,  // 6: account.AccountService.Credit:input_type -> account.CreditRequest
	7,  // 7: account.AccountService.Debit:input_type -> account.DebitRequest
	8,  // 8: account.AccountService.CommitReservation:input_type -> account.CommitReservationRequest
	9,  // 9: account.AccountService.CancelReservation:input_type -> account.CancelReservationRequest
	10, // 10: account.AccountService.Create:output_type -> account.AccountResponse
	10, // 11: account.AccountService.GetByID:output_type -> account.AccountResponse
	11, // 12: account.AccountService.Block:output_type -> account.Empty
	11, // 13: account.AccountService.Unblock:output_type -> account.Empty
	11, // 14: account.AccountService.Close:output_type -> account.Empty
	11, // 15: account.AccountService.Reserve:output_type -> account.Empty
	11, // 16: account.AccountService.Credit:output_type -> account.Empty
	11, // 17: account.AccountService.Debit:output_type -> account.Empty
	11, // 18: account.AccountService.CommitReservation:output_type -> account.Empty
	11, // 19: account.AccountService.CancelReservation:output_type -> account.Empty
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_server_proto_account_proto_init() }
func file_server_proto_account_proto_init() {
	if File_server_proto_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_account_proto_rawDesc), len(file_server_proto_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_account_proto_goTypes,
		DependencyIndexes: file_server_proto_account_proto_depIdxs,
		MessageInfos:      file_server_proto_account_proto_msgTypes,
	}.Build()
	File_server_proto_account_proto = out.File
	file_server_proto_account_proto_goTypes = nil
	file_server_proto_account_proto_depIdxs = nil
}
