global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:8080"]

  - job_name: "account-service"
    static_configs:
      - targets: ["account-service:9001"]

  - job_name: "transaction-service"
    static_configs:
      - targets: ["transaction-service:9002"]
