name: CI Main

on:
  push:
    branches: [main]

jobs:
  ci:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/reusable.yaml
    with:
      image_tag: stable
      push_latest: false
      push_dev: false
    secrets: inherit