name: CI Main

on:
  push:
    branches: [main]

jobs:
  ci:
    uses: ./.github/workflows/reusable.yaml
    with:
      image_tag: stable
      push_latest: false
      push_dev: false
    secrets:
      ghcr_token: ${{ secrets.GHCR_TOKEN }}