name: CI Release

on:
  push:
    branches:
      - 'release/**'

jobs:
  ci:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/reusable.yaml
    with:
      image_tag: latest
      push_latest: true
      push_dev: false
    secrets: inherit