name: CI Release

on:
  push:
    branches:
      - 'release/**'

jobs:
  ci:
    uses: ./.github/workflows/reusable.yml
    with:
      image_tag: latest
      push_latest: true
      push_dev: false
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}